// --------------------------
// Do not edit this file.
// --------------------------

$(document).ready(function() {
    if (typeof hello == 'function') {
        $(".container h1").html(hello());
    }

    $(".container button").click(function() {
        if (typeof greet === 'function') {
            alert(greet($("form input").val()));
        }
    });
});