// --------------------------
// Do not edit this file.
// --------------------------

var orders = [];

$(document).ready(function() {
    $(".container button").click(function() {
        var name = $(".container input[name=name]").val();
        var price = parseFloat($(".container input[name=price]").val());

        item = createItem(name, price);
        orders = addOrder(orders, item);

        var html = "";
        for (var i=0; i < orders.length; i++) {
            html += "<li>" + orders[i].name + ": $" + orders[i].price + "</li>";
        }

        $("#orders").html(html);
        $("#tip").html("Tip: $" + tip(orders));
        $("#total").html("Total: $" + total(orders));

        return false;
    });
});