// --------------------------
// Do not edit this file.
// --------------------------

var orders=[];$(document).ready(function(){$(".container button").click(function(){var a=$(".container input[name=name]").val();var d=parseFloat($(".container input[name=price]").val());item=createItem(a,d);orders=addOrder(orders,item);var c="";for(var b=0;b<orders.length;b++){c+="<li>"+orders[b].name+": $"+orders[b].price+"</li>"}$("#orders").html(c);$("#tip").html("Tip: $"+tip(orders));$("#total").html("Total: $"+total(orders));return false})});